### ISSUE TITLE
Breaking up seats for screen reader users

### ISSUE THREAD

**Issue by adamsilver** [adamsilver/f#117]
A: A Boeing 747 commerical jet airliner has over 400 seats so we've more shattered, than broken the 7 choice rule. Call me a rebel, but I'm struggling to see a better way of presenting seats. Choosing a seat is quite a unique interaction and benefits from this layout.

H: I'm wondering how this could be broken up, but see the nested fieldset issue. Maybe `<div>`s around discrete sections (economy/first class, or however you want to divide it up) with `role="region"` and a complementary `aria-label`. These would act as group labels plus the region role provides a navigation mechanism in screen readers (region shortcut key). Then users could more easily switch between larger areas of the map.

**Comment by Heydon** [comment]
@adamsilver Lost some text there?

**Comment by adamsilver** [comment]
Thanks @Heydon - didn't wrap the code bits.

**Comment by adamsilver** [comment]
Optional discussion point.
