### ISSUE TITLE
Links between form controls for sighted users: issues for screen readers?

### ISSUE THREAD

**Issue by adamsilver** [adamsilver/f#129]
> Worse is when the link is placed before the submit button. When keyboard users tab from the password field and press Enter, they'll expect the form to submit.

H: Clear focus styles permitting, is this really a problem for sighted keyboard users?

**Comment by adamsilver** [comment]
I've seen others experience this. Then I asked Twitter this morning — fancy retweeting it? :)

https://twitter.com/adambsilver/status/939741043418951680

**Comment by Heydon** [comment]
@adamsilver 👍 Leave it in, but address any additional issues for screen reader users

**Comment by adamsilver** [comment]
Ask Heydon what these additional issues are—I can't think of one.

**Comment by adamsilver** [comment]
Screen reader (keyboard) users wouldn't discover it without moving past the form (main call to action).
