### ISSUE TITLE
An expense form (Heydon various)

### ISSUE THREAD

**Issue by Heydon** [adamsilver/f#141]
> At first I wanted to fold this chapter into the last one because there's some overlap. Adding multiple files needn't be different from adding multiple of anything else really. It's just that uploading files has some unique considerations (such as drag and drop) that made sense to tackle in isolation.

As an explanation for why you were going to fold this chapter into the last, this isn't much cop as there's no reason — at this stage — why the reader might expect an expense form to be about uploading (multiple) files. As in the previous chapter, you sometimes talk to yourself rather than the reader and things are left unclear.

I imagine there are also lots of different ways of reporting expenses, so this cryptic conception of an expense form (so far unillustrated) may not match what a user expects.

> Unlike file inputs, other form controls don't let you add multiple values.

They don't? What about checkbox groups, or `<select>` controls with the `multiple` attribute (for example)?

> **The Ever Present Form Pattern**

You completely lose me here :-) The first two paragraphs explaining the pattern leave me wondering what is 'ever-present' about it and in what respects other form patterns are not. Is this an established term for the pattern?

> Also, there are multiple buttons: one to submit and one to proceed which could be confusing

There are? Where? Again, it feels like you're referring to something that only exists in your head ;-) The Github example only uses one button, right? I think you need to illustrate/code a version of the expenses form that _does_ use this pattern, before moving onto the one-thing-per-page alternative.

> Also, each submission is a server request.

It is? In the Github example or where? Need to tie things down.

> Imagine you need to add a bunch of expenses, but the type of expense determines the information you need to enter. For example, if you're expensing a car, then you have to enter mileage, but if you're expensing a train ticket then you have to enter the ticket price.

I expect expenses will be claimed differently per reader and some readers will never have claimed expenses. Please set out more clearly in the introduction what you are going to make before you make it. Then, even if it is unfamiliar, at least it will have an internal logic that you have conveyed.

> This is because it guides the user to provide the right information at the right time, which is especially useful for cognitively impaired users.

Why? (Also, the Github example — which is the only thing I really have to go on at this stage — is only adding multiples of the same thing, on a single page, so a "One Thing Per Page" alternative wouldn't make sense anyway.)

> The degraded experience is the same, except clicking a button refreshes the page.

Degraded how? I think too many are unfamiliar with progressive enhancement for you to just drop this in without explanation.

> Instead, we should set focus to the heading at the beginning of the form.

You need to explain why this is okay and how it is achieved.

> Cloning Explained

You explain that you are cloning things, but not why — at least not from the outset. There is a weird thing sometimes where you seem to explain the detail of something _then_ set out the context and why you are doing it. Try to reorder so that what you are trying to achieve and why is set out first.

> Every time the user adds or removes an item, we need to do some important work behind the scenes. Cloning works by taking the first item in the list, and cloning it. But this isn't enough on its own because this clones everything: id and name attributes included.

See what I mean? Why do you need to do the cloning in the first place? I'm sure there are other ways to create new expense entries, like using a `<template>` element (?) I'm missing what cloning really achieves and why it is the best way of doing that thing (is it?)

You also omit the code that actually does the cloning. This might help to explain the process.

> As laid out in, chapter 2, “A Checkout Flow”, the name of each radio button is the same, but the id need to be unique of course.

You can rewrite this as a reminder of why: "As laid out in, chapter 2, “A Checkout Flow”, the name of each radio button is the same because it identifies the set to which they belong. The id identifies the individual radio button."

> digital ability

What is digital ability?

No checklist?

**Done! This one needs more work than most; I think maybe you spent less time on it than the earlier chapters? Nothing that can't be salvaged, though, so no worries!**

**Comment by adamsilver** [comment]
- As a contractor I have to submit expenses for my tax return. It’s a pain, and if I do it correctly I get tax breaks. The problem is that theres multiple expenses, what’s the best pattern for that? The anatomy of an expense. name, tracking number, currency, amount, proof, date. Distill it.
- Framing the problem, framing the pattern - what sort of pattern would solve this problem.
