### ISSUE TITLE
Heydon review

### ISSUE THREAD

**Issue by Heydon** [adamsilver/f#91]
> They just want access to it, the tools you offer or the promise of a faster experience next time.

Couple of issues here:
1. I think "tools you offer" is too specific and techie centric
2. Surely it should be _and_ not_or_?

"*They just want to access what you are offering, with the promise that they can access it _faster_ next time they visit*"? Maybe a bit long...

> Whatever it is, a registration form is often the first form a user sees.

Often, I find it's the login form they see first, with the registration form hidden behind a link / small button. A usability issue in itself?

> the primitive elements that make up a form (labels, buttons and inputs), how to reduce friction (even on small forms like this) all the way through to form validation.

"How to reduce friction" is very idiomatic, and I'm not sure what you mean. Maybe should be "reduce friction when x" or "reduce friction while x". If you mean "confusion" or "frustration", maybe say that instead.

```html
<input type="submit" value="Register">
```
> Why not `<button type="submit"></button>`? I prefer this, but I'm not sure why :-) Maybe because it has a text node, and can be styled with the same `button` selector as non-submit buttons?

> The form is made up 4 fields and a submit button.

*made up _of_

> By looking at labels from each of these standpoints, we can see just how important labels are. Sighted users can read them, visually-impaired users can hear them by using a screen reader and motor-impaired users can more easily set focus to the field thanks to the larger hit area. That's because clicking a label sets focus to the field.

Great stuff! Maybe just replace "field" with "associated form element" in the last sentence so it sounds less redundant, and clarifies.

> Submit buttons, for example, don't accept input so they don't need a label - the value attribute which renders the text inside the button acts as the accessible label.

Careful! You do clarify that the submit needs a label, of course — but you should start out with *"don't accept input so they don't need an **auxiliary** label"*. 

> Failing to include a label means ignoring the needs of (motor and visually-impaired) users.

Also cognitively impaired users. Having explained earlier on why labels benefit all type of people, I'm not sure you should be specific here. Maybe *"Failing to include a label means ignoring the needs of many users, including those with physical and cognitive disabilities. By focusing on the recognized barriers of people with disabilities, we can make our forms easier and more ribust for everyone."*

Dunno. Something like that?

> The placeholder attribute is intended to store a hint. It gives users extra guidance when filling out a field - particularly useful for fields that have complex rules such as a password field.

Glad you spelled this out. Most people are awful for misusing placeholders.

![grey placeholder](https://user-images.githubusercontent.com/683558/32990175-8eb87520-cd1c-11e7-98d6-cf793c26fc83.png)

I think the color contrast issue is worth mentioning here, as well as your reasoned argument about it disappearing.

> some screen readers don't announce them and long hint text may get cut off.

Good point! I'd not considered that one.

> The aria-describedby attribute is used to connect the hint by its id

Just like the `for` attribute for labels, but in reverse!

> First, clicking the hint (a <p> in this case) won't focus the control, which reduces the hit area. Second, despite ARIA's ever-growing support, it's never going to be as well supported as native elements. This is why the first rule of ARIA is not to use ARIA:

I think you should provide support data to support (no pun intended) this. IE11 seems to be an issue: http://www.html5accessibility.com/tests/aria-labelledby-input.html.

> While this provides similar behaviour, these two solutions are not created equal.

The trouble here, is that you already describe a difference in the paragraph above this one?

> Second, they're hard-to-read due to their (affordance giving) poor contrast

What do you mean by "(affordance giving)" here? I think you should either remove or unpack this.

> Quirky and minimalist interfaces don't make users feel awesome. Obvious, inclusive and robust interfaces do. 

👏

> which may drive users crazy

I'm not personally offended by this, but some would consider 'crazy' ableist. *"Why may make users angry"*?

> Clicking it, logs the user into the service immediately.

No comma needed.

> Whilst this reduces friction on the form in isolation, in other ways it adds some too.

There's that friction thing you keep talking about :-) "reduces friction on the form in isolation" sounds especially clumsy and I'm unclear what it means. *"Whilst this reduces form complexity..."*?

> Broadly speaking, you should place the label above the form control. 

You can't place something in a specific place broadly :-) Maybe *"With few exceptions, you should..."*.

> In “Label Placement In Forms”^6, Matteo Penzo shows this is best. But, there are more practical reasons for doing so.

I don't think comparing "best" with "practical" is very fruitful here. If not practical, what do you mean by best? I think you should be more specific about Matteo's claims.

> Also, some labels contain a lot of text which causes it to wrap onto multiple lines which would disrupt the visual rhythm if placed next to the control.

Side comment, but have you noticed that putting things next to things on the web is almost always the wrong idea? 😆

> Whilst you should aim to keep labels terse, it's not always possible. So, using a pattern that accomodates varying content - by positioning labels above the control - is a good strategy.

👏

> You might be tempted to remove this styling for aesthetic reasons but again, that's hardly a good reason to diminish the experience. If you wish to remove it, then make sure you replace it with something more preferable.

I think you should advocate for strong focus styles here. Default styles for form elements are very faint in many browsers. Maybe a code example for a thicker `outline` like

```css
input:focus {
    outline: 4px solid;
}
```

> The label itself is “Email address” and uses sentence case.

In the mobile version of the form (in the picture) it's "E-mail", though...?

> When things go wrong — and they will — users shouldn't suffer. That's bad design.

Not sure about this. If something has gone wrong, aren't they already suffering. Maybe you mean, they don't "suffer too much" or "can still get things done".

Also, I think "That **would** be bad design" because it's a hypothetical you are trying to avoid.

> Users are left unharmed.

RE `border-radius`, I think you need to be clear where the hypothetical harm might come from. E.g. `border-radius` not being supported might instead cause the page to error and elements not to render.

> In other cases you might need to detect support using Feature Queries[^].

Not sure if you go into feature queries later, but you kind of name drop them without explanation here.

> This can mean not all of the script executes.

Worth mentioning the knock-on effect here — that it can cause other (valid and supported) scripts not to execute or to otherwise fail too.

> It's the content that counts and Javascript doesn't give you that.

I'm worried that someone facetious will point out that JavaScript is _often_ used to deliver content, whether by `createElement` or a fully-fledged framework. Perhaps explain why client-side JS rendering is bad here.

> There's no point in enhancing something if it doesn't add value

Maybe link to that specific principle (http://inclusivedesignprinciples.org/#add-value).

> But if we follow the principles above, when the browser or network fails things will still work.

Fails completely? Because I think you'd be out of luck then. Maybe "experiences failures"?

> “over the shoulder” attacks

Sounds more... physical than intended, I think?

> If you're using a template language, then you'll be able to abstract this into a component which will ensure that every field is styled consistently throughout the application

Probably nit picking but, to me, this sounds like you're saying "will make every field like a password field".

> Instead, it's better to let users reveal their password which speaks to principles 4 and 5, Give control and Offer choice respectively. This way users get the security of the mask without increasing the risk of typos.

To be clear, they don't "get the security of the mask" while the masking is turned off — which is what the feature you're discussing is for. Maybe talk about how they can choose when to reveal the password, when they know nobody is looking.

> When clicked, it should toggle the type attribute between password and text and the label between “Show password” and “Hide password”.

I like this method, but just to note: you could also use a toggle button or checkbox and leave the label consistent.

```js
function PasswordReveal(el) {
  this.el = el;
  this.createButton();
};

PasswordReveal.prototype.createButton = function() {
  this.button = $('<button type="button">Show password</button>');
  $(this.el).parent().append(this.button);
  this.button.on('click', $.proxy(this, 'onButtonClick'));
};

PasswordReveal.prototype.onButtonClick = function(e) {
  if(this.el.type === 'password') {
    this.el.type = 'password';
    this.button.text('Show password');
  } else {
    this.el.type = 'text';
    this.button.text('Hide password');
  }
};
```

Been a long time since I wrote jQuery, so just wondering aloud:
* Is this.el = el necessary?
* Is augmenting the prototype necessary? Wouldn't you usually use `on` or `addEventListener`?
* Could you use a ternary for the type / label switches?

I think you should step through what the script does in more detail, or add comments. 

> Where “Password” is ambiguous, “Choose passwrod” provides clarity.

*password ;-)

> Links are typically underlined or specially positioned in a navigation bar so that they are visually identifiable amongst regular text.

Typically -> by user agents styles. Probably worth mentioning.

> Buttons can still give feedback on hover by changing the background colour for example.

Or focus! Often styling hover and focus the same way is a nice touch.

> **Button Styles**

May cause confusion that you used an `<input type="submit">` rather than a `<button>`

> Eye tracking tests prove this to be the case.

I don't doubt it, but [needs citation] if you're going to say "prove". To me, it just stands to reason.

> We should aim to use as fewer words as possible because less words are quicker to read.

"as fewer" -> "as few"
"less" -> "few"

> our user's are none the wiser

Spotted a few stray apostrophes like this. Owen will catch them, so not worrying too much.

> Updating the title with Javascript is as follows:

I'm personally try to say 'as follows' less, so I feel inclined to say suggest *"The following JavaScript updates the title:"*. More direct, I think.

> This time, the updated title acts as a notification in the tab.

I'm not sure what I'm supposed to see in the image, but the title just says "Unstyled"?

> You might use position, size, text and iconography in addition to colour.

It's confusing, because the example provided doesn't provide any of these signifiers (except perhaps bold text?) Position maybe, but since the image is isolated, you don't know the position.

> Clicking a link, will set focus to the erroneous field thanks to the href value matching the form control's id value. This let's users jump into the form quickly.

I beleieve some browsers will not actually move focus to the linked field unless it has `tabindex="-1"`. I really like this technique, though.

```
<div class="errorSummary" role="alert" tabindex="-1" aria-labelledby="errorSummary-heading">
  <h2 id="errorSummary-heading">There's a problem</h2>
  <ul>
    <li><a href="#emailaddress">Enter an email address</a></li>
    <li><a href="#password">The password must contain an uppercase letter</a></li>
  </ul>
</div>
```

Can confirm that focusing this with Voiceover on Chrome reads out the `<a>` label and the rest of the live region contents. I like this, but not sure it's what you were going for. Will test further in other AT when I get to the component library.

> To hide the panel we need to add a class of `hidden`.

I remember us discussing your reasons for class versus `hidden` attribute. Maybe explain them here?

![email field with error](https://user-images.githubusercontent.com/683558/32991041-42b4da1e-cd2c-11e7-8928-75a836e936a8.png)

Where did the description/extended label go? Is it replaced by this? I was thinking that, in many cases, descriptions could act as error messages anyway, so I think you just need to add the red (and a warning symbol, as we discussed) and add `aria-invalid`.

```
var validator = new FormValidator(document.getElementById('registration'));
```

Where does `FormValidator` come from? I'm not sure you mention it. Is it part of jQuery? Your own validation script? Another module? I don't think there's any reason to be prescriptive about how the form is validated, so maybe present it as an example library.

> To create an instance of FormValidator you need to pass the form element as the first parameter.

This is under **Technical Design**. I'm thinking it would make more sense to introduce the technical dependency of `FormValidator` and how it works before talking about how you harness it. Feels a bit back to front at the moment (see previous comment).

> user's minds

* users' minds

> For entries that require a certain number of characters, the first keystroke will always constitute an invalid entry. This means users will be interrupted early and often causing them to switch mental contexts. That is, between entering information and fixing it.

Well explained / argued.

> Some forms will disable the submit button until all the form fields are valid. This leaves users wondering what's actually wrong with their entries. Instead, keep users in control by allowing them to submit when they're ready. When they do submit, form validation will be on-hand to provide useful feedback.

You should note that disabled buttons are not focusable. This makes it hard for the button to be discovered using some software. It's expected that buttons become unfocusable when disabled, but in some circumstances it may be confusing. In this case, and as you've set validation / error reporting out, there's no reason for it because one would submit a form with errors or without.

> Putting labels and hints inside form fields.

This is under **Things To Avoid**. I may be missing something, but surely hints _are_ okay inside fields? That's what `placeholder` is for?

**Done!** Language section was really strong, I thought. 👏

**Comment by adamsilver** [comment]
Closing as I've fixed many of the issues. For the remaining ones, I've moved into issues of their own and tagged them accordingly.
